[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_solana = "14rCPGC8a8eUiLkdvCRTsritjZk98BKtTP8LzpArhu6q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/akshit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
